name = "airgas-telegram-bot"
main = "telegram-bot-worker.js"
compatibility_date = "2026-02-27"

[[kv_namespaces]]
binding = "CHAT_STATE"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_YOUR_KV_PREVIEW_NAMESPACE_ID"
